import React, { useState, useEffect } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import   
 AllBots from '../components/AllBots'; // Import the AllBots component
import { BotStruct, RootState } from '../store/type.dt';
import { createBot, getAllBots } from "../services/ServerCall";
import { useDispatch, useSelector } from 'react-redux';
import { sendEthToEveryBot } from '../services/Blockchain';

const Home: NextPage = () => {
  const { Bots } = useSelector((states: RootState) => states.globalStates);
  const [bots, setBots] = useState([]);
  const dispatch = useDispatch();

  useEffect(() => {
    const fetchBots = async () => {
      const data = await getAllBots();
      setBots(data);
    };
    fetchBots();
  }, []);

  const handleCreateNewBot = async () => {
    await createBot();
    const data = await getAllBots();
      setBots(data);
  }
  const handleSendEth = async() => {
    await sendEthToEveryBot(bots);
    const data = await getAllBots();
    setBots(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico"   
 rel="icon" />
      </Head>

      <main className={styles.main}>   

        <div className='gap-5 h-auto'>
          <div className='h-[15vh] w-[100%] flex flex-col gap-5 '>

          <button onClick={handleCreateNewBot} className='inline-flex w-[90%] justify-center rounded-lg bg-cyan-600 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-cyan-700 focus:outline-none focus:ring-4 focus:ring-cyan-200 dark:focus:ring-cyan-900'>Create New Bot</button>
          {/* <button onClick={handleSendEth} className='inline-flex w-[90%] justify-center rounded-lg bg-cyan-600 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-cyan-700 focus:outline-none focus:ring-4 focus:ring-cyan-200 dark:focus:ring-cyan-900'>Send eth to every bot</button> */}
          </div>
          {Bots.length > 0 && ( // Conditionally render bot information
            <AllBots bots={bots} /> // Pass bots data to the AllBots component
          )}
        </div>

      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at   
 
        </a>
      </footer>
    </div>
  );
};

export default Home;