const superCharacters = [
    "Solarion",
    "Terraformer",
    "Superman",
    "Batman",
    "Wonder Woman",
    "Forrest",
    "Marty",
    "Luke",
    "Han",
    "Leia",
    "Indiana",
    "Jack",
    "Rose",
    "Neo",
    "Trinity",
    "Gandalf",
    "Aragorn",
    "Frodo",
    "Sam",
    "Legolas",
    "James",
    "Bond",
    "Ethan",
    "Hunt",
    "Rick",
    "Blaine",
    "Rick",
    "Sanchez",
    "Archer",
    "Sterling",
    "Lana",
    "Cyril",
    "Pam",
    "Cheryl",
    "Klaus",
    "Peter",
    "Venkman",
    "Egon",
    "Ray",
    "Winston",
    "John",
    "McClane",
    "Bruce",
    "Wayne",
    "Alfred",
    "Joker",
    "Clark",
    "Kent",
    "Lois",
    "Lex",
    "Tyler",
    "Durden",
    "Marla",
    "Jack",
    "Sparrow",
    "Will",
    "Turner",
    "Elizabeth",
    "Swann",
    "Barbossa",
    "Dorian",
    "Gray",
    "Basil",
    "Rathbone",
    "Sherlock",
    "Holmes",
    "John",
    "Watson",
    "Harry",
    "Potter",
    "Ron",
    "Hermione",
    "Draco",
    "Severus",
    "Snape",
    "Albus",
    "Dumbledore",
    "Rubeus",
    "Hagrid",
    "Remus",
    "Lupin",
    "Sirius",
    "Black",
    "Peter",
    "Pettigrew",
    "John",
    "Connor",
    "Sarah",
    "Connor",
    "Kyle",
    "Reese",
    "Terminator",
    "Ash",
    "Williams",
    "Ellen",
    "Ripley",
    "Gordon",
    "Gekko",
    "Bud",
    "Fox",
    "Michael",
    "Corleone",
    "Vito",
    "Corleone",
    "Tom",
    "The Flash",
    "Green Lantern",
    "Aquaman",
    "Martian Manhunter",
    "Cyborg",
    "Green Arrow",
    "Hawkgirl",
    "Nightwing",
    "Batgirl",
    "Supergirl",
    "Shazam",
    "Booster Gold",
    "Blue Beetle",
    "Firestorm",
    "Atom",
    "Black Canary",
    "Zatanna",
    "Plastic Man",
    "Elongated Man",
    "Vixen",
    "Captain Marvel",
    "Doctor Fate",
    "Deadman",
    "Swamp Thing",
    "Animal Man",
    "Starfire",
    "Raven",
    "Lex Luthor",
    "The Joker",
    "Brainiac",
    "Sinestro",
    "Black Manta",
    "Cheetah",
    "Darkseid",
    "Doomsday",
    "Deathstroke",
    "Reverse-Flash",
    "Captain Cold",
    "Heat Wave",
    "Gorilla Grodd",
    "Poison Ivy",
    "Scarecrow",
    "Bane",
    "Harley Quinn",
    "Two-Face",
    "Penguin",
    "Riddler",
    "Catwoman",
    "Black Adam",
    "Circe",
    "Ocean Master",
    "Trigon",
    "Deathstroke",
    "Black Mask",
    "Mr. Freeze",
    "Killer Croc",
    "Mad Hatter",
    "Beast Boy",
    "Quantum Leap",
    "Chronomaster",
    "Nebula",
    "Echo",
    "Void",
    "Zephyr",
    "Ignis",
    "Hydro",
    "Electra",
    "Cryogen",
    "Titan",
    "Velocity",
    "Mindwarp",
    "Illusionist",
    "Invincible",
    "Healer",
    "Animalia",
    "Technopath",
    "Astronaut",
    "Phaser",
    "Invisible",
    "Soundwave",
    "Elastic",
    "Forcefield",
    "Regenerator",
    "Shapeshifter",
    "Telepath",
    "Telekinetic",
    "Nemesis",
    "Chaos",
    "Dominator",
    "Phantom",
    "Corruptor",
    "Conqueror",
    "Mutator",
    "Mindbender",
    "Reaper",
    "Infector",
    "Inferno",
    "Tempest",
    "Shadowlord",
    "Enigma",
    "Overlord",
    "Destructor",
    "Manipulator",
    "Nightmare",
    "Parasite",
    "Toxic",
  ];
  
  const config = {
    dictionaries: [superCharacters],
    style: "capital",
    randomDigits: 2,
  };

  module.exports = config;